name: planet_pets_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  fluttertoast: ^8.0.9

  cloud_firestore: ^3.1.18
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  firebase_messaging: ^11.4.2
  firebase_storage: ^10.2.18
  provider: ^6.0.3
  url_launcher: ^6.1.4
  http: ^0.13.4
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^0.8.5+3
  dot_navigation_bar: 1.0.1+4
  path_provider: ^2.0.11

  shared_preferences: ^2.0.15
  email_validator: ^2.0.1
  google_sign_in: ^5.3.3

  get: 4.6.5
  flutter:
    sdk: flutter
  firebase_auth_web: ^3.3.17
  firebase_messaging_web: ^2.4.2
  firebase_storage_web: ^3.2.17

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/rafiki.png
    - assets/images/rafiki2.png
    - assets/images/rafiki3.png
    - assets/images/PPLogo.png
    - assets/images/google_icon.png
    - assets/images/UserIcon.png
    - assets/images/Top.png
    - assets/images/Cat.png
    - assets/images/Dog.png
    - assets/images/Fish.png
    - assets/images/Bird.png
    - assets/images/placeholder-image.png
    - assets/images/loading.gif
    - assets/images/user_placeholder.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
